name: cloudassist
description: A cloud learning database app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+15

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Auth
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^5.0.0

  #Data
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  #Firebase
  cloud_firestore: ^4.9.3
  cloud_functions: ^4.4.2
  firebase_analytics: ^10.5.1
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  # firebase_database: ^10.2.3
  firebase_storage: ^11.2.8

  #Networking
  http: ^1.1.0
  url_launcher: ^6.1.7

  # State Management
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  observable: ^0.24.0

  #UI
  curved_navigation_bar: ^1.0.3
  google_fonts: ^6.1.0
  responsive_framework: ^1.1.1
  flutter_neumorphic: ^3.2.0
  expandable: ^5.0.1
  nil: ^1.1.1
  showcaseview: ^2.0.0+1
  styled_widget: ^0.4.1
  fade_shimmer: ^2.2.0
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  syncfusion_flutter_charts: ^23.1.40

  #Misc
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  go_router: ^11.1.4
  shared_preferences: ^2.0.18
  flutter_tts: ^3.6.3
  mockito: ^5.4.0
  flutter_hooks: ^0.20.3

  
  
dev_dependencies:
#  flutter_test:
#    sdk: flutter
  go_router_builder: ^2.3.3
  build_verify: ^3.1.0
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
