import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `user_model.dart` with the code generated by Freezed
part 'user_model.freezed.dart';
// optional: Since our UserModel class is serializable, we must add this line.
// But if UserModel was not serializable, we could skip it.
part 'user_model.g.dart';

///Model for cloud data
class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();

  @override
  DateTime fromJson(Timestamp json) => json.toDate();

  @override
  Timestamp toJson(DateTime object) => Timestamp.fromDate(object);
}

class TimestampNullableConverter implements JsonConverter<DateTime?, Timestamp?> {
  const TimestampNullableConverter();

  @override
  DateTime? fromJson(Timestamp? json) => json?.toDate();

  @override
  Timestamp? toJson(DateTime? object) =>
      object == null ? null : Timestamp.fromDate(object);
}

@freezed
class UserModel with _$UserModel {
  const factory UserModel({
    required String displayName,
    required String email,
    required String photoURL,
    required String uid,
    required bool paid,
    @TimestampConverter() DateTime?  dateCreated,
  }) = _UserModel;

  factory UserModel.fromJson(Map<String, Object?> json) =>
      _$UserModelFromJson(json);
}

UserModel defaultUserModel = UserModel(
    displayName: 'displayName',
    email: 'user.user.com',
    photoURL: 'photoURL',
    uid: 'uid',
    paid: false,
    dateCreated: DateTime.now());
    
