import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `user_interaction_model.dart` with the code generated by Freezed
part 'user_interaction.freezed.dart';
// optional: Since our UserInteractionModel class is serializable, we must add this line.
// But if UserInteractionModel was not serializable, we could skip it.
part 'user_interaction.g.dart';

///Model for user_interaction data

class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();

  @override
  DateTime fromJson(Timestamp json) => json.toDate();

  @override
  Timestamp toJson(DateTime object) => Timestamp.fromDate(object);
}

class TimestampNullableConverter
    implements JsonConverter<DateTime?, Timestamp?> {
  const TimestampNullableConverter();

  @override
  DateTime? fromJson(Timestamp? json) => json?.toDate();

  @override
  Timestamp? toJson(DateTime? object) =>
      object == null ? null : Timestamp.fromDate(object);
}

@freezed
class UserInteractionModel with _$UserInteractionModel {
  const factory UserInteractionModel({
     String? serviceId,
     String? featureId,
    @TimestampConverter() DateTime? startTime,
    @TimestampConverter() DateTime? endTime,
  }) = _UserInteractionModel;

  factory UserInteractionModel.fromJson(Map<Object?, Object?> json) =>
      _$UserInteractionModelFromJson(json);
}
