// ignore_for_file: non_constant_identifier_names

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `agent_data_model.dart` with the code generated by Freezed
part 'agent_data_model.freezed.dart';
// optional: Since our AgentData class is serializable, we must add this line.
// But if AgentData was not serializable, we could skip it.
part 'agent_data_model.g.dart';

///Model for agent data
class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();

  @override
  DateTime fromJson(Timestamp json) => json.toDate();

  @override
  Timestamp toJson(DateTime object) => Timestamp.fromDate(object);
}

class TimestampNullableConverter implements JsonConverter<DateTime?, Timestamp?> {
  const TimestampNullableConverter();

  @override
  DateTime? fromJson(Timestamp? json) => json?.toDate();

  @override
  Timestamp? toJson(DateTime? object) =>
      object == null ? null : Timestamp.fromDate(object);
}

@freezed
class AgentData with _$AgentData {
  const factory AgentData(
      {required String agent,
      required String context,
      required Map<String, Object?> response,
      required String response_id,
      @TimestampConverter() DateTime?  timestamp,
      required String topic_id,
      required String user_id}) = _AgentData;

  factory AgentData.fromJson(Map<String, Object?> json) =>
      _$AgentDataFromJson(json);
}

AgentData defaultAgentData = const AgentData(
    agent: 'agent',
    context: 'context',
    response:  <String, dynamic>{},
    response_id: 'response_id',
    topic_id: 'topic_id',
    user_id: 'user_id');

    
// dart run build_runner build --delete-conflicting-outputs
