import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `report_model.dart` with the code generated by Freezed
part 'report_model.freezed.dart';
// optional: Since our ReportModel class is serializable, we must add this line.
// But if ReportModel was not serializable, we could skip it.
part 'report_model.g.dart';

///Model for report data

class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();

  @override
  DateTime fromJson(Timestamp json) => json.toDate();

  @override
  Timestamp toJson(DateTime object) => Timestamp.fromDate(object);
}

class TimestampNullableConverter
    implements JsonConverter<DateTime?, Timestamp?> {
  const TimestampNullableConverter();

  @override
  DateTime? fromJson(Timestamp? json) => json?.toDate();

  @override
  Timestamp? toJson(DateTime? object) =>
      object == null ? null : Timestamp.fromDate(object);
}

@freezed
class ReportModel with _$ReportModel {
  const factory ReportModel({
    required String content,
    required String docID,
    required List<String> tags,
    required String title,
    @TimestampConverter() DateTime? timestamp,
  }) = _ReportModel;

  factory ReportModel.fromJson(Map<String, Object?> json) =>
      _$ReportModelFromJson(json);
}
