import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `database_architecture_model.dart` with the code generated by Freezed
part 'database_architecture_model.freezed.dart';
// optional: Since our DatabaseArchitecture class is serializable, we must add this line.
// But if DatabaseArchitecture was not serializable, we could skip it.
part 'database_architecture_model.g.dart';

///Model for cloud data
@freezed
class DatabaseArchitecture with _$DatabaseArchitecture {
  const factory DatabaseArchitecture(
      {required String question,
      required List<String> answers,
}) = _DatabaseArchitecture;

  factory DatabaseArchitecture.fromJson(Map<String, Object?> json) =>
      _$DatabaseArchitectureFromJson(json);
}

    
// flutter pub run build_runner build --delete-conflicting-outputs
